
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "80:80"

  mariadb:
    build: requirements/mariadb  # Ensure you have a Dockerfile inside srcs/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    env_file:
      - .env

networks:
  app-network:

volumes:
  mariadb_data:

