volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/inception/data/wp
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/inception/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    expose:
      - "9000"
    image: wordpress:42
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
